### DISCUSSION TITLE
Method does not exist - client.query$GetUserPreferences

### DISCUSSION THREAD

**Discussion by ptheofan** [heftapp/graphql_codegen#259] [Q&A]
Just trying to figure out how to make full use of the package. So far it seems that all of the expected `client.query$.... ` are missing and the `Options$Query$...` classes are also missing. All help is appreciated.

# The Setup

```yml
# pubspec.yml
dependencies:
  flutter:
    sdk: flutter
  graphql_codegen: ^0.12.0-beta.15
  graphql_flutter: ^5.1.2
  graphql: ^5.1.3
```

```yml
# build.yml
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
            - graphql_flutter
          scalars:
            URL:
              type: String
            ISODateTime:
              type: DateTime
              fromJsonFunctionName: dateTimeFromJson
              toJsonFunctionName: dateTimeToJson
              import: package:testing/domain/scalars.dart
```

```graphql
# schema.graphql
input UserPreferencesInput {
    userId: String!
    themeMode: ThemeMode
    themeName: String
}

type UserPreferencesModel {
    userId: String!
    themeMode: ThemeMode
    themeName: String
}

type Query {
  userPreferencesGet(userId: String!): UserPreferencesModel!
}
```

```graphql
# get_user_preferences.graphql
# This is the gql query I intend to run
query GetUserPreferences($userId: String!) {
    userPreferencesGet(userId: $userId) {
        userId
        themeMode
        themeName
    }
}
```

and building all using
```shell
flutter pub run build_runner build --delete-conflicting-outputs
```

The generated `get_user_preferences.graphql.dart` includes
```
Variables$Query$GetUserPreferences
Query$GetUserPreferences
Query$GetUserPreferences$userPreferencesGet
```

# Making a call

```dart
final GraphQLClient client = GraphQLClient(link: httpLink, cache: GraphQLCache());
final data = await client.query$GetUserPreferences(
  Options$Query$GetUserPreferences(
    variables: Variables$Query$GetUserPreferences(userId: userId),
  ),
);
```

and here I get the error `Method does not exist` for `client.query$GetUserPreferences`. Also the class `Options$Query$GetUserPreferences` does not exist.

Is there some other `client` I should be using instead of the one coming from the graphql package? Why is the Options class missing? All help is appreciated.
