### DISCUSSION TITLE
onComplete is not called when executing query

### DISCUSSION THREAD

**Discussion by JuliusFreudenberger** [heftapp/graphql_codegen#363] [Q&A]
I try to use the `onComplete` callback with mutations and queries. The mutations work fine as I expect; however I have problems with the `onComplete` callback.

My `pubspec.yaml` looks like this:
```yaml
dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.2.0-beta.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  graphql_codegen: ^1.0.1
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
```
The code I use to execute the query looks like this (I omitted unrelated stuff and generalized some names):
```dart
final result = await client.query$OperationName(
      Options$Query$OperationName(
        variables: Variables$Query$OperationName(
          variableName: value,
        ),
        fetchPolicy: FetchPolicy.networkOnly,
        typedOptimisticResult: Query$OperationName(),
        onError: (error) => // Handle error,
        onComplete: (_, parsedData) {
          print("onComplete Callback called");
        },
      ),
    );
final parsedData = result.parsedData;
// Do something with the data
```

The `print()`-Statement is not executed and the message does not appear on the console.
Am I doing something wrong? 
I am quite confident I have the latest versions of the related dependency, but do I maybe need to update a dependency?
