### ISSUE TITLE
Incorrect slashes in the fragment import path

### ISSUE THREAD

**Issue by Exeteres** [heftapp/graphql_codegen#1]
Thanks for the great package! Everything works as expected except for one thing.

Slashes in the generated files are turned in the wrong direction, which causes a compilation error.
Most likely the current implementation of the path joining is platform dependent (I am using Windows).

![image](https://user-images.githubusercontent.com/29506045/123954708-e8619180-d9d2-11eb-94df-f6b12c687221.png)

**Comment by mvarendorff** [comment]
Hey there! I found the same issue trying out this package yesterday. A fix is available on my fork and can be used until the PR above is merged with this dependency:

```yaml
dev_dependencies:
  graphql_codegen:
    git:
      url: https://github.com/mvarendorff/graphql_codegen
      ref: fix/import-path
      path: graphql_codegen
```
