### ISSUE TITLE
Path generation is broken with a custom outputDirectory [0.10.0-beta.3]

### ISSUE THREAD

**Issue by motrieux-thomas** [heftapp/graphql_codegen#110]
Hello,

It seems that there is a problem when generating certain imports with the latest beta version.  [0.10.0-beta.3]

The generator created this :
import '../../../../../../repositories/my_schema/schema.graphql.dart';

But the correct one is this :
import '../../../../../../../repositories/kp_commodities/__generated__/schema.graphql.dart';

**My config file :** 
```
graphql_codegen:
        options:
          outputDirectory: '__generated__'
          scopes:
            - lib/**/my_schema/**
          clients:
            - graphql
            - graphql_flutter
          namingSeparator: ''
```

Don't hesitate to reach me if you need more informations.
