### ISSUE TITLE
Generator not generating .g files

### ISSUE THREAD

**Issue by mario-jerkovic** [heftapp/graphql_codegen#118]
**Version:** graphql_codegen: 0.10.0-beta.5

Generator finds `.graphql` files but fails to generate `.g` files which are referenced in `schema.graphql.dart` with `part 'schema.graphql.g.dart';`

build.yaml
```yaml
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          outputDirectory: '__generated__'
          namingSeparator: ''
          addTypename: true
          scalars:
            DateTime:
              type: DateTime
            JSON:
              type: Map<String, dynamic>
            Upload:
              type: String
          clients:
            - graphql
```

generated files
![Screenshot 2022-07-13 at 14 29 45](https://user-images.githubusercontent.com/16222284/178733767-932fc3d1-2748-478e-b5ca-e6a33a2d2f53.png)
![Screenshot 2022-07-13 at 14 30 11](https://user-images.githubusercontent.com/16222284/178733838-2b2eb253-ff23-4322-b429-22eaa83286f9.png)
)
