### ISSUE TITLE
Import errors if schema outside lib/ directory

### ISSUE THREAD

**Issue by baconcheese113** [heftapp/graphql_codegen#137]
If you move your schema outside of the `lib/` directory, say to `graphql/` in the root folder and generate the schema you'll get errors in every file that includes the generated schema files.

This is with 
```yaml
# build.yaml
targets:
  $default:
    sources: # configuration used with Artemis to place schema.graphql outside lib/
      - lib/**
      - graphql/**
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
            - graphql_flutter
          scalars:
            DateTime:
              type: DateTime
          outputDirectory: __generated__
          assetsPath: "**.graphql"
```

Example of import that reports error:
```dart
import '../../../../../graphql/__generated__/schema.graphql.dart';
```
