### ISSUE TITLE
Issue with JSON scalar type

### ISSUE THREAD

**Issue by eapCJ** [heftapp/graphql_codegen#165]
Hi,

Configuring the build.yaml with a scalar of type json mapped as a Map<String,dynamic> is failing. 

codegen.graphql.dart:
![codegen.graphql.dart](https://user-images.githubusercontent.com/30572988/184947813-dda3174d-0f11-4eb2-9c3f-c8555b4ed0c9.png)

build.yaml:
```yaml
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          namingSeparator: "$"
          includeIfNullOnInput: false
          clients:
            - graphql
            - graphql_flutter
          scalars:
            json:
              type: Map<String, dynamic>
            jsonb:
              type: Map<String, dynamic>
``` 

schema.graphql:
```graphql
input JsonbCastExp {
  String: StringComparisonExp
}

"""
Boolean expression to compare columns of type "jsonb". All fields are combined with logical 'AND'.
"""
input JsonbComparisonExp {
  _cast: JsonbCastExp

  """is the column contained in the given json value"""
  _containedIn: jsonb

  """does the column contain the given json value at the top level"""
  _contains: jsonb
  _eq: jsonb
  _gt: jsonb
  _gte: jsonb

  """does the string exist as a top-level key in the column"""
  _hasKey: String

  """do all of these strings exist as top-level keys in the column"""
  _hasKeysAll: [String!]

  """do any of these strings exist as top-level keys in the column"""
  _hasKeysAny: [String!]
  _in: [jsonb!]
  _isNull: Boolean
  _lt: jsonb
  _lte: jsonb
  _neq: jsonb
  _nin: [jsonb!]
}
```
