### ISSUE TITLE
`schema.graphql.dart` is empty after running `build_runner`

### ISSUE THREAD

**Issue by JordyLangen** [heftapp/graphql_codegen#179]
I've set up a simple project, and set up `graphql_codegen` & `build_runner`. When using the schema from Gitlab (see below), it generates an empty `schema.graphql.dart`. I've added another `.graphql` file, for which everything seems to be generated except for the "clients" queries.

pubspec.yaml:

```yaml
dependencies:
  args:
  graphql:
  json_annotation: 4.6.0
  json_serializable:

dev_dependencies:
  build_runner:
  graphql_codegen:
```

build.yaml:

```yaml
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
```

gitlabs schema.graphql:
https://gist.github.com/JordyLangen/949ba96c8a326a5e3c9088d8d734f35d
