### ISSUE TITLE
Field named `default` breaks generation

### ISSUE THREAD

**Issue by arnemolland** [heftapp/graphql_codegen#184]
I've got a field called `default` in my schema:

```graphql
type Foo {
  default: Boolean
}
```

Which causes the build runner to fail
```
[SEVERE] graphql_codegen on lib/graphql/fragments.graphql:

Could not format because the source could not be parsed:

line 2, column 11 of .: 'default' can't be used as an identifier because it's a keyword.
  ╷
2 │ bool? get default;
  │           ^^^^^^^
  ╵
line 265, column 11 of .: 'default' can't be used as an identifier because it's a keyword.
    ╷
265 │ bool? get default;
    │           ^^^^^^^
    ╵
line 373, column 11 of .: 'default' can't be used as an identifier because it's a keyword.
    ╷
373 │ bool? get default;
    │           ^^^^^^^
    ╵
[SEVERE] Failed after 213ms
pub finished with exit code 1
```

And I've added `default` as an extra keyword in my build config (even though it's there by default):
```yaml
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql_flutter
          outputDirectory: /lib/graphql/gen
          extraKeywords:
            - default
```

Am i missing something here?
