### ISSUE TITLE
[documentation]: Change folder generated with .g.dart

### ISSUE THREAD

**Issue by Kiruel** [heftapp/graphql_codegen#188]
Could be good to add in the documentation, how to change the generated folder with the `.g.dart` included, this is my `build.yaml` to generate all `.grapqhql.dart` AND `.g.dart` in the generated folder:

```yaml
targets:
  $default:
    sources:
      - graphql/**
      - $package$
      - lib/**
      - pubspec.*
      - generated/**
    builders:
      source_gen:combining_builder:
        options:
          build_extensions: {
            'lib/features/{{}}.dart': 'lib/generated/features/{{}}.g.dart',
            'lib/core/{{}}.dart': 'lib/generated/core/{{}}.g.dart',
            'lib/generated/{{}}.dart': 'lib/generated/{{}}.g.dart'
          }
      graphql_codegen:
        options:
          outputDirectory: /lib/generated
          clients:
            - graphql
            - graphql_flutter
```

Now every files generated is in the `/lib/generated/` folder. And got a clean `lib/features` and `lib/core` with only `.graphql` files.
