### ISSUE TITLE
Enum custom serialization on build.yaml

### ISSUE THREAD

**Issue by williamhjcho** [heftapp/graphql_codegen#223]
Hello 👋 

## Issue

Would it be possible to add custom serialization for **enum** types on `build.yaml`?

```yaml
# example build.yaml

targets:
  $default:
    builders:
      graphql_codegen:
        options:
          # ... other options
          
          scalars: # or enums (?)
            # ... other customizations
            CountryCode:
              type: CountryCode
              fromJsonFunctionName: CountryCode.parse
              toJsonFunctionName: countryCodeToJson
              import: package:my_package/my_packagedart
```

## Context

We already had an `enum CountryCode` that contains some more complex properties, and we wanted to avoid using the schema's simple enum, and maybe avoid generating it at all if possible.

One way we could try avoiding this issue right now, is by type converting them before sending the request & deserializing, so the callers aren't aware of `Enum$CountryCode` at all.
But if the property is located in a sufficiently nested field, we have to do deep copies just to avoid using the type, which is not ideal but doable.
