### ISSUE TITLE
Custom scalar type isn't found in generated files

### ISSUE THREAD

**Issue by BaudouinCS** [heftapp/graphql_codegen#228]
Hello!

I've defined a new scalar `Metadata` in my `schema.graphql`, implemented it in my `scalars.dart` as such:
```dart
import 'package:myapp/models/metadata_model.dart';

// ... other scalars

Metadata metadataToJson(Metadata data) => Metadata.toJson(data);

Metadata metadataFromJson(String json) => Metadata.fromRawJson(json);
```
and defined it in my `build.yaml` like this:
```yaml
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scalars:
            # ... other scalars
            Metadata:
              type: Metadata
              fromJsonFunctionName: metadataFromJson
              toJsonFunctionName: metadataToJson
              import: package:myapp/graphql/schemas/scalars.dart
          clients:
            - graphql
            - graphql_flutter
```
After that I can successfully run `flutter packages pub run build_runner build --delete-conflicting-outputs` in my terminal, but when I try to build my app to test it out, it says it can't find the Metadata type in my generated files:
```bash
[+11899 ms] [+11797 ms] lib/graphql/schemas/user.graphql.dart:1147:9: Error: Type 'Metadata' not found.
[  +13 ms] [   +7 ms]   final Metadata metadata;
[        ] [        ]         ^^^^^^^^
```

Is there something I did wrong somewhere? I already re-read the documentation about custom scalars but couldn't find anything different...
