### ISSUE TITLE
Absolute output directory not working

### ISSUE THREAD

**Issue by kentnek** [heftapp/graphql_codegen#229]
Hi, I have the following project structure:
```
graphql
  - schemaA
    - *.graphql files
  - schemaB
    - *.graphql files

lib
  - generated
    - schemaA
    - schemaB
  - src
```

I'd like `graphql_codegen` to parse the `.graphql` files in `graphql` folder and generated Dart classes in `lib/generated`. Here's my config:
```yaml
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - $package$
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
          assetsPath: graphql/**
          scopes:
            - graphql/schemaA/**
            - graphql/schemaB/**
          outputDirectory: /lib/generated
```
However no files are generated. If I replace `/lib/generated` with `lib/generated`, the Dart files are generated relative to the `graphql` files, which is not what I want. Is this a bug?

**Comment by budde377** [comment]
What system are you running this on?

**Comment by kentnek** [comment]
Windows 11, latest `graphql_codegen` version.

**Comment by budde377** [comment]
This is a bit hard for me to debug. Can you try and change the dependency to

```yaml

  graphql_codegen:
    git:
      url: https://github.com/heftapp/graphql_codegen.git
      ref: fix-absolute-output-dir-win
      path: packages/graphql_codegen
```

**Comment by kentnek** [comment]
> This is a bit hard for me to debug. Can you try and change the dependency to
> 
> ```yaml
>   graphql_codegen:
>     git:
>       url: https://github.com/heftapp/graphql_codegen.git
>       ref: fix-absolute-output-dir-win
>       path: packages/graphql_codegen
> ```

hi, this works perfectly! thank you.

**Comment by kentnek** [comment]
One more question: I'd like to use `Decimal` as a scalar, so I specify the following config:
```yaml
Decimal:
  type: Decimal
  fromJsonFunctionName: decimalFromJson
  toJsonFunctionName: decimalToJson
  import: package:app/src/utils/scalars.dart
```
where `package:app/src/utils/scalars.dart` contains the functions `decimalFromJson` and `decimalToJson`. 
However the generated Dart files don't have the import for the `Decimal` type itself (`package:decimal/decimal.dart`). How do I add that automatically?

**Comment by budde377** [comment]
Awesome! I'll do a release soon.
Regarding the imports, what do you need to do here is explicitly exporting the Decimal scalar from the file with your converter implementation (app/src/utils/scalars.dart).

So something like

```dart
export 'decimal' show Decimal;
```

**Comment by budde377** [comment]
Finally got to release it! It should be out as `0.12.0-beta.7`

**Comment by Mastermori** [comment]
I am having the same issue with the newest version (0.13.5). Generating with a relative path works fine, but an absolute path generates nothing.
My build.yaml looks like this:
```
targets:
  $default:
    sources:
      - graphql/**
      - lib/**
      - pubspec.*
      - $package$
    builders:
      graphql_codegen:
        options:
          outputDirectory: /lib/generated
          assetsPath: graphql/**
```
Sadly I could not try the fix by using an updated dependency, as the branch seems to no longer exist.
