### ISSUE TITLE
Incompatible versions : graphql_codegen x graphql_flutter 

### ISSUE THREAD

**Issue by Msartre** [heftapp/graphql_codegen#236]
Hi, 

For a project, we are working with graphql_flutter >=5.1.2, that depends on graphql ^5.1.3 which depends on **gql ^0.14.0**. And, it seems that versions 5.1.2 of graphql_flutter and 0.11.2 of graphql_codegen are not compatible since it depends on **gql ^0.13.0**. 

Here are my dependencies : 
```
dependencies:
  flutter:
    sdk: flutter
  
  graphql_flutter: ^5.0.0
  flutter_hooks: ^0.18.5+1
  graphql_codegen: ^0.11.2

```
 And here is the error message in my console : 
```
Because no versions of graphql_codegen match >0.11.2 <0.12.0 and graphql_codegen 0.11.2 depends on gql ^0.13.0, graphql_codegen ^0.11.2 requires gql ^0.13.0.
And because graphql_flutter >=5.1.2 depends on graphql ^5.1.3 which depends on gql ^0.14.0, graphql_codegen ^0.11.2 is incompatible with graphql_flutter >=5.1.2.
So, because test_grapqhql depends on both graphql_flutter ^5.1.2 and graphql_codegen ^0.11.2, version solving failed.
pub get failed (1; So, because test_grapqhql depends on both graphql_flutter ^5.1.2 and graphql_codegen ^0.11.2, version solving failed.)
```

Sorry if this issue has already been signaled (but I couldn't see it anywhere). 

Many thanks !
