### ISSUE TITLE
Nothing is being generated when using most basic example

### ISSUE THREAD

**Issue by wolframm** [heftapp/graphql_codegen#241]
I'm doing the following:

`flutter create -t package graph_ql`
`cd graph_ql`
`flutter pub add --dev graphql_codegen build_runner`
`flutter pub add graphql graphql_flutter flutter_hooks`
`mkdir schema`

I put the following two files into the `schema` dir:

```
# schema.graphql

type Query {
    fetch_person(id: ID!): Person
}

type Person {
    full_name: String!
    nickname: String
    website: URL
    date_of_birth: ISODateTime
    parents: [Person!]
    siblings: [Person!]
    children: [Person!]
}

scalar ISODateTime

scalar URL
```
and
```
# person.graphql

query FetchPerson($id: ID!) {
  fetch_person(id: $id) {
    name: full_name
  }
}
```
I also create the following `build.yaml` in the package root:
```
# build.yaml

targets:
  $default:
    builders:
      graphql_codegen:
        options:
          assetsPath: schema/**.graphql
```

Then I run: `dart run build_runner build`.

Build runner prints:

```
Building package executable... (5.5s)
Built build_runner:build_runner.
[INFO] Generating build script completed, took 353ms
[INFO] Precompiling build script... completed, took 5.6s
[INFO] Building new asset graph completed, took 524ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Running build completed, took 3ms
[INFO] Caching finalized dependency graph completed, took 34ms
[INFO] Succeeded after 45ms with 0 outputs (0 actions)
```
Then I look into my `schema` folder... and there is nothing! Please let me know how I can generate some Dart code.

`dart info`:
```
#### General info

- Dart 2.19.0 (stable) (Mon Jan 23 11:29:09 2023 -0800) on "macos_x64"
- on macos / Version 13.1 (Build 22C65)
- locale is en-US

#### Project info

- sdk constraint: '>=2.19.0 <3.0.0'
- dependencies: flutter, flutter_hooks, graphql, graphql_flutter
- dev_dependencies: build_runner, flutter_lints, flutter_test, graphql_codegen
```

`flutter doctor`:
```
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

```
# pubspec.yaml

name: graph_ql
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  graphql: ^5.1.1
  graphql_flutter: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  graphql_codegen: ^0.11.2
  build_runner: ^2.3.3
```
