### ISSUE TITLE
Allow custom unknown enum fallback case provided on the build.yaml

### ISSUE THREAD

**Issue by williamhjcho** [heftapp/graphql_codegen#261]
Hello 👋 

Feature request for allowing custom enum values to be provided as fallbacks when generating enums, for example:

given a known schema enum:

```graphql
enum MyEnum {
  FIRST
  LAST
  OTHER # or UNKNOWN
}
```

with a build.yaml

```yaml
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          enums:
            MyEnum:
              fallback: OTHER
```

would not generate the `MyEnum.$unknown` and would use the OTHER whenever applicable instead

This is most useful when the schema enum already has an `UNKNOWN` case, and the codegen generates an extra `$unknown` case
