### ISSUE TITLE
Error in generating dart code for queries that use interfaces types

### ISSUE THREAD

**Issue by RoliThePoli** [heftapp/graphql_codegen#264]
A query that I need to use in the project, returns an interface type. In the schema, there are specified a couple of implementations for this interface. If I try to use an implementation as the return type for the query, and generate the code from that, it doesn't work. Since the package doesn't see the expect type (the interface from the schema query), it's not able to generate the variables from the implemented type correctly. It generates an empty class.

Query:
```
getSimpleProductOffering(
    " SEO qualifier of product and its dimensions (eq: color, size) "
    productBySeoInput: ProductBySeoInput!
  ): ProductOffering!
```

Product Offering type in schema:
```
type ProductOffering {
  " Own prices of product "
  prices: [Price!]!
  " Details of product "
  product: Product!
}
```

Product Interface:
```
interface Product {
  code: String!
  " Particular Product's name "
  name: String!
}
```

MarketplaceDevice implementation for Product interface:
```
type MarketplaceDevice implements GenericDevice & Product {
  baseDeviceName: String!
  baseDeviceSeoId: String!
  "A brief description of the basic device that may vary depending on whether the user is currently authenticated"
  baseDeviceShortDescription: String
  categoryPath: [Category!]!
  "Unique product identifier in the shop domain."
  code: String!
  "List of descriptions for the device variant"
  descriptions: [String!]!
  "Requested product variant dimensions. For example, color, capacity, etc. Each type of device may have its own set of dimensions."
  dimensions: [Dimension!]!
  features: [Feature!]
  "List of images of the Product."
  images: [Image!]!
  keywords: String
  manufacturer: String
  "Marketing name of the product."
  name: String!
  " Description of the product which is used by search engines "
  seoDescription: String!
  seoTitle: String
  specifications: [Specification!]!
  "The Stock status of the Product."
  stockStatus: StockLevelStatus!
}
```

This is how we created the query on our side:
```
query  GetSimpleProductOffering($productBySeoInput: ProductBySeoInput!) {
  getSimpleProductOffering(productBySeoInput: $productBySeoInput) {
    ...ProductOffering
  }
}
```

And the Product Offering fragment:
```
fragment ProductOffering on ProductOffering{
  prices {
    ...PriceFragment
  }
  product {
    ... on MarketplaceDevice {
      ...MarketplaceDevice
    }
  }
}
```

We tried to rewrite the query in multiple ways: with fragments, without fragments, etc. In every version we get an empty generated class for the MarketplaceDevice attributes, like this:
```
class Fragment_ProductOffering_product {
  Fragment_ProductOffering_product();

  factory Fragment_ProductOffering_product.fromJson(Map<String, dynamic> json) {
    return Fragment_ProductOffering_product();
  }

  Map<String, dynamic> toJson() {
    final _resultData = <String, dynamic>{};
    return _resultData;
  }

  @override
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    if (!(other is Fragment_ProductOffering_product) ||
        runtimeType != other.runtimeType) {
      return false;
    }
    return true;
  }
}
```

If we only include directly in the query, the variables from the interface only, they show up. As soon as you extend that with attributes from the implemented version, it doesn't do anything.

**Comment by budde377** [comment]
What version of the generator are you using?

**Comment by budde377** [comment]
And can you share your config?

**Comment by RoliThePoli** [comment]
@budde377 we're using graphql_codegen: ^0.11.2 with these overriden dependencies because of conflicts with other packages:
dependency_overrides:
  gql_code_builder: ^0.5.1
  gql: ^0.13.0

**Comment by budde377** [comment]
Are you able to try the pre release?

**Comment by budde377** [comment]
Can you share your build config?

**Comment by RoliThePoli** [comment]
@budde377 
```
targets:
  $default:
    builders:
      graphql_codegen:
        enabled: true
        options:
          addTypename: false
          namingSeparator: '_'
          scalars:
            DateTime:
              type: DateTime
              fromJsonFunctionName: dateTimeFromJson
              toJsonFunctionName: dateTimeToJson
              import: ../scalars/scalars.dart
            ZonedDateTime:
              type: DateTime
              fromJsonFunctionName: dateTimeFromJson
              toJsonFunctionName: dateTimeToJson
              import: ../scalars/scalars.dart
            LocalizedString:
              type: Map<String,dynamic>
            Long:
              type: int
              fromJsonFunctionName: intFromJson
              toJsonFunctionName: intToJson
              import: ../scalars/scalars.dart
            Double:
              type: double
              fromJsonFunctionName: doubleFromJson
              toJsonFunctionName: doubleToJson
              import: ../scalars/scalars.dart

          clients:
            - graphql
```
