### ISSUE TITLE
Printer error: Unsupported scalar ISODateTime

### ISSUE THREAD

**Issue by phuocbitmark** [heftapp/graphql_codegen#268]
Hi, how do i fix this.
I've already added file build.yaml:
```yaml
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scalars:
            ISODateTime:
              type: DateTime
            JSON:
              type: Map<String, dynamic>
```
