### ISSUE TITLE
question: Multipart file upload, scalar inside the type

### ISSUE THREAD

**Issue by kamilkarp** [heftapp/graphql_codegen#305]
I'm using scalar File to handle Multipart file upload. Is it possible to use it inside another type?

When I'm using file in mutation directly its all fine:
`uploadMultipleFiles(files: [File!]!) : Response`

But when I try to have the File inside the type like this, generator fails:
```
type ImageFile {
    file: File!
    height: Int!
    width: Int!
}
```

Config:
```
MultipartFile fileFromJson(dynamic data) {
  return data as MultipartFile;
}

dynamic fileToJson(ImageFileType data) {
  return data;
}
```

In build.yaml:

```
scalars:
   File:
      type: MultipartFile
      fromJsonFunctionName: fileFromJson
      toJsonFunctionName: fileToJson
````
