### ISSUE TITLE
Custom scalars do not work with "input types"

### ISSUE THREAD

**Issue by naedx** [heftapp/graphql_codegen#342]
The code builder fails with `[SEVERE] Failed after ...` when using a custom scalar inside the definition of an input type as seen in `input Animal` below:

```graphql
# schema.graphql

type Person {
  id: String
  createdAt: AWSDateTime
}

input Animal {
  id: String
  createdAt: AWSDateTime
}

```

```yaml
# build.yaml

targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scalars:
              AWSDateTime:
                type: String

```

I would expect that the library would honor the configs for the input types as well.

### Use case
AWS Amplify generates schema for the AppSync API which includes input types with their custom scalars.
