### ISSUE TITLE
Timestamptz should use toUtc().toIso8601String()

### ISSUE THREAD

**Issue by orestesgaolin** [heftapp/graphql_codegen#364]
There's a type [`timestamptz` in PostgreSQL](https://hasura.io/blog/postgres-date-time-data-types-on-graphql-fd926e86ee87) database that includes a tz information (timezone offset). When using it with default DateTime as type in build runner configuration, it may lead to errors where timezone gets lost.

build.yaml:
```
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scalars:
            timestamptz:
              type: DateTime
```

In Dart if DateTime is in the local timezone of the device the call to `toIso8601String()` results with a string without `Z` in the local timezone of the device. When sent via graphql mutation to a PostgreSQL database it will be interpreted as if this was in the UTC timezone.

```
  // in UTC+1 timezone
  final date = DateTime(2024,01,01,01);

  print(date.toUtc()); // 2024-01-01 00:00:00.000Z
  print(date.toIso8601String()); // 2024-01-01T01:00:00.000
  print(date.toUtc().toIso8601String()); // 2024-01-01T00:00:00.000Z
```

I suggest that graphql_codegen should include default `timestamptz` converter, e.g. something like:

```dart
DateTime timestamptzFromJson(String json) {
  return DateTime.parse(json);
}

String dateToJson(DateTime object) {
  return object.toUtc().toIso8601String();
}
```

```yaml
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scalars:
            ISODateTime:
              type: DateTime
            timestamp:
              type: DateTime
            timestamptz:
              type: DateTime
              fromJsonFunctionName: timestamptzFromJson
              toJsonFunctionName: dateToJson
              import: package:my_package/my_package.dart
```
