### ISSUE TITLE
How can I handle List of Scalar

### ISSUE THREAD

**Issue by samuelchanx** [heftapp/graphql_codegen#45]
Thanks for the great library. I'm trying to migrate our use case from [Artemis](https://github.com/comigor/artemis/). May I know how to handle List of objects and Nullable case of the scalar?

For example, in my schema.graphql, I have a scalar of date. And in some cases, we need to use [date]!. Given the following build.yaml config, the generation outputs errors. 

```
date:
    type: DateTime
    fromJsonFunctionName: fromGraphQLDateNullableToDartDateTimeNullable
    toJsonFunctionName: fromDartDateTimeNullableToGraphQLDateNullable
    import: package:app/data/model/scalar/graphql_scalar.dart
```

Errors from build_runner: 
![image](https://user-images.githubusercontent.com/6096534/157632820-45afceac-8090-423f-9e8e-6f292be80f42.png)
