### ISSUE TITLE
question: how to handle multipart file upload

### ISSUE THREAD

**Issue by fionues** [heftapp/graphql_codegen#71]
I am using codegen with [graphql](https://pub.dev/packages/graphql) as a client. I struggle with uploading files. [graphql](https://pub.dev/packages/graphql) supports MultipartFile upload (https://pub.dev/packages/graphql#graphql-upload) but i dont understand how to integrate this with codegen. How can i specify the scalar for the Upload type?
Do I have to wrap it in my own class to link it in the build.yaml or can i reference it directly? If so, how would this be done?

**Comment by IluhinDotPro** [comment]
**build.yaml**
```
targets:
  $default:
    builders:
      json_serializable:
        options:
          include_if_null: false
      graphql_codegen:
        options:
          includeIfNullOnInput: false
          clients:
            - graphql
          scalars:
            DateTime:
              type: DateTime
              fromJsonFunctionName: dateTimeFromJson
              toJsonFunctionName: dateTimeToJson
              import: package:yourapp/scalars.dart
            JSON:
              type: Map<String, dynamic>
            Upload:
              type: MultipartFile
              fromJsonFunctionName: fileFromJson
              toJsonFunctionName: fileToJson
              import: package:yourapp/scalars.dart

```

**lib/scalars.dart**
```
import "package:http/http.dart";
export "package:http/http.dart";

String dateTimeToJson(DateTime data) {
  return data.toIso8601String();
}

DateTime dateTimeFromJson(dynamic data) {
  return DateTime.parse(data);
}

MultipartFile fileFromJson(dynamic data) {
  return data as MultipartFile;
}

dynamic fileToJson(MultipartFile data) {
  return data;
}

```

in code..
  ```
Future<bool> uploadImage(String fileNameId) async {
    final ImagePicker _picker = ImagePicker();
    final XFile? image = await _picker.pickImage(source: ImageSource.gallery);
    if (image == null) return false;
    print(image.path);

    var result = await _client.mutateUploadUserFile(
      OptionsMutationUploadUserFile(
        variables: VariablesMutationUploadUserFile(
          file: MultipartFile.fromBytes(
            "",
            await image.readAsBytes(),
            filename: fileNameId,
            contentType: MediaType.parse(lookupMimeType(image.path)!),
          ),
        ),
      ),
    );
    if (result.hasException) {
      print(result.exception.toString());
      await Sentry.captureException(result.exception);
      return false;
    }
    print(result.parsedData!.toJson());
    return true;
  }
```
