### ISSUE TITLE
No generation for graphql_flutter client

### ISSUE THREAD

**Issue by ShooTeX** [heftapp/graphql_codegen#78]
It's the first time i'm using this package, somehow it doesn't generate the flutter widgets.
changing `clients` in `build.yaml` does generate outputs but they look the same.

`build.yaml`
```yaml
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
            - graphql_flutter
```

`get_all_pokemons.graphql`
```graphql
query AllPokemons {
  pokemon_v2_pokemonspecies(order_by: {id: asc}) {
    name
    id
  }
}
```

`get_all_pokemons.graphql.dart`
```dart
import 'package:json_annotation/json_annotation.dart';
part 'get_all_pokemons.graphql.g.dart';

@JsonSerializable()
class QueryAllPokemons extends JsonSerializable {
  QueryAllPokemons(this.pokemon_v2_pokemonspecies);

  @override
  factory QueryAllPokemons.fromJson(Map<String, dynamic> json) =>
      _$QueryAllPokemonsFromJson(json);

  final List<QueryAllPokemons$fpokemon_v2_pokemonspecies>
      pokemon_v2_pokemonspecies;

  @override
  Map<String, dynamic> toJson() => _$QueryAllPokemonsToJson(this);
}

@JsonSerializable()
class QueryAllPokemons$fpokemon_v2_pokemonspecies extends JsonSerializable {
  QueryAllPokemons$fpokemon_v2_pokemonspecies(this.name, this.id);

  @override
  factory QueryAllPokemons$fpokemon_v2_pokemonspecies.fromJson(
          Map<String, dynamic> json) =>
      _$QueryAllPokemons$fpokemon_v2_pokemonspeciesFromJson(json);

  final String name;

  final int id;

  @override
  Map<String, dynamic> toJson() =>
      _$QueryAllPokemons$fpokemon_v2_pokemonspeciesToJson(this);
}
```
`get_all_pokemons.graphql.g.dart`
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'get_all_pokemons.graphql.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

QueryAllPokemons _$QueryAllPokemonsFromJson(Map<String, dynamic> json) =>
    QueryAllPokemons(
      (json['pokemon_v2_pokemonspecies'] as List<dynamic>)
          .map((e) => QueryAllPokemons$fpokemon_v2_pokemonspecies.fromJson(
              e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$QueryAllPokemonsToJson(QueryAllPokemons instance) =>
    <String, dynamic>{
      'pokemon_v2_pokemonspecies': instance.pokemon_v2_pokemonspecies,
    };

QueryAllPokemons$fpokemon_v2_pokemonspecies
    _$QueryAllPokemons$fpokemon_v2_pokemonspeciesFromJson(
            Map<String, dynamic> json) =>
        QueryAllPokemons$fpokemon_v2_pokemonspecies(
          json['name'] as String,
          json['id'] as int,
        );

Map<String, dynamic> _$QueryAllPokemons$fpokemon_v2_pokemonspeciesToJson(
        QueryAllPokemons$fpokemon_v2_pokemonspecies instance) =>
    <String, dynamic>{
      'name': instance.name,
      'id': instance.id,
    };
```

`pubspec.yaml`
```yaml
name: pokedex
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-109.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.1.0
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  graphql_codegen: ^0.0.1-alpha.1

flutter:

  uses-material-design: true
```

build_runner build output:

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 284ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 48ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 550ms

[INFO] Running build...
[INFO] Running build completed, took 14ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 29ms

[INFO] Succeeded after 51ms with 0 outputs (0 actions)
```
